spring:
  web:
    locale: en_US
  jackson:
    default-property-inclusion: non_null
  datasource:
    password: bbiu-pwd
    url: jdbc:h2:~/bbiu-db;AUTO_SERVER=TRUE
    username: bbiu
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
server:
  error:
    include-binding-errors: always
    include-message: always


