-- Noughts
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought1', 4.5, 'BLACK', 'This is Nought 1');
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought2', 6.2, 'RED', 'This is Nought 2');
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought3', 5.8, 'GREEN', 'This is Nought 3');
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought4', 7.1, 'BLUE', 'This is Nought 4');
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought5', 4.2, 'YELLOW', 'This is Nought 5');
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought6', 5.5, 'BLACK', 'This is Nought 6');
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought7', 6.8, 'RED', 'This is Nought 7');
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought8', 7.3, 'GREEN', 'This is Nought 8');
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought9', 4.8, 'BLUE', 'This is Nought 9');
INSERT INTO NOUGHTS (ID, NAME, RADIUS, COLOR, COMMENT) VALUES (NEXTVAL('NOUGHTS_SEQ'), 'Nought10', 5.7, 'YELLOW', 'This is Nought 10');

-- Crosses
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross1', 43, 1, 1, 'WOOD', 'This is Cross 1');
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross2', 22, 2, 2, 'WOOD', 'This is Cross 2');
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross3', 9, 3, 3, 'WOOD', 'This is Cross 3');
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross4', 31, 4, 4, 'WOOD',  'This is Cross 4');
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross5', 17, 5, 5, 'WOOD', 'This is Cross 5');
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, EXPIRY_DATE, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross6', 6, 6, 1, 'METAL', NOW() - INTERVAL '1' DAY, 'This is Cross 6');
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, EXPIRY_DATE, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross7', 28, 7, 2, 'METAL', NOW() - INTERVAL '2' DAY, 'This is Cross 7');
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, EXPIRY_DATE, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross8', 12, 8, 3, 'METAL', NOW() + INTERVAL '5' DAY, 'This is Cross 8');
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, EXPIRY_DATE, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross9', 38, 9, 4, 'METAL', NOW() + INTERVAL '1' MONTH, 'This is Cross 9');
INSERT INTO CROSSES (ID, NAME, ANGLE, WEIGHT, BEAMS, MATERIAL, EXPIRY_DATE, COMMENT) VALUES (NEXTVAL('CROSSES_SEQ'), 'Cross10', 14, 10, 5, 'METAL', NOW() + INTERVAL '1' YEAR, 'This is Cross 10');
